[6268] Update SDK packages
craftercms/video-center-blueprint pull request #219
Opened 2023-11-01 16:29 UTC by jvega190

https://github.com/craftercms/craftercms/issues/6268

2023-11-07 14:40 UTC, sumerjabri commented
@jvega190 please pull and rebuild the code because deps were updated. (Be careful not to mess up the `yarn.lock`.)

2023-11-09 22:29 UTC, jvega190 commented
This is ready for merge and it's compatible with 4.1.2

2023-11-16 15:26 UTC, rart requested changes
Apply to other bps

2023-11-16 15:26 UTC, rart commented on sources/app/build.sh
> +vite build
won't work out of IntelliJ

2023-11-16 15:26 UTC, rart commented on craftercms-plugin.yaml
> +    patch: 52
Must add 4.1.2 to the compatible versions

2023-11-17 21:13 UTC, jvega190 commented on craftercms-plugin.yaml
> +    patch: 52
4.1.2 is already added in all bps (for branch 'next')

2023-12-18 16:23 UTC, rart approved these changes

2023-12-18 16:29 UTC, merged